### ISSUE TITLE
更详细的信息吗

### ISSUE THREAD

**Issue by monkeydone** [baojiweicn/susnote#1]
是否有演示地址和安装文档.

**Comment by baojiweicn** [comment]
我今晚会把详细的文档写上来。
另外也会做一个docker，直接通过docker部署。

**Comment by baojiweicn** [comment]
@lijunjieone https://github.com/baojiweicn/susnote/blob/server/Document/How_To_Install.md
添加了如何使用docker安装，具体请看文档。
add how to install by docker, look up the link pls.
